### PR TITLE
Use neostandard + add more static code analysis 

### PR DESCRIPTION
**Pull request by voxpelli**
This replaces `standard` with `neostandard` and:

* adds the result of running a `npx eslint --fix`
* removes no longer supported `/* eslint-env mocha */` and replaces it with `env: ['mocha']` in the `neostandard` config (it adds it globally, but I think that's okay for this project, a more deluxe solution would be to instead do: https://github.com/voxpelli/eslint-config/blob/main/base-configs/mocha.js)
* adds a `neostandard` badge, I opted for the one without the neostandard colors 😜 

Also:

* adds `rimraf`, because there's a dependency on it that worked when `standard` made it be included
* adds `knip` to help avoid the above
* cleaned up stuff and refactored some stuff to help `knip`
* added `installed-check` to ensure that the engine range is good

### CODE REVIEW

**Comment by bcomnes** [comment]
Thanks for doing all of that. No breaking changes right?

**Review by bcomnes — APPROVED** [review]

**Comment by voxpelli** [comment]
Only such change would be the narrowing of the engine definition to match that of the dependencies, else nothing 😌

**Comment by voxpelli** [comment]
@bcomnes You want me to merge or you will merge? :)

**Comment by bcomnes** [comment]
I won't have time till later so feel free.

**Pull request merged**
