### PR TITLE
Remove rimraf devdep

### PR DESCRIPTION
**Pull request by bcomnes**
Remove rimraf as a dev dep. One less thing to update.

### CODE REVIEW

**Review by voxpelli — APPROVED** [review]
As long as the tests still pass on Windows I’m 🙌

**Comment by TWiStErRob** [comment]
Hmm, I have a feeling that the docs should keep the `rimraf` there so the "recommendation" is to support multiplatform builds?

**Comment by bcomnes** [comment]
I know github action windows runners support rm -rf directly now, is that a gha specific feature?

Alternatively could we instead recommend windows users use wsl for multiplatform builds? 

My goal is to eliminate random one off solutions like rimrad when there are better platform solutions available now.

**Comment by TWiStErRob** [comment]
I'm not sure it's GHA only. I'll check what's available to confirm if this actually affects pure Windows (non-WSL) developer machines.

**Comment by XhmikosR** [comment]
FYI this breaks native Windows cmd and requires a unix environment, so WSL, MSYS, etc.

**Comment by bcomnes** [comment]
Wsl should work. Posh has rm -rf now right? Git bash is also a good option on windows. GitHub action windows runners have rm -rf now. Besides this is just used in testing and docs, people are free to use rimraf as needed. I just don't want to keep updating this dep since it doesn't seem that critical here.

**Comment by voxpelli** [comment]
@XhmikosR Do you know how this can be the case then?

> I know github action windows runners support rm -rf directly now, is that a gha specific feature?

Are GitHub:s runners not representative of a normal windows box? Does it run a different version of windows to what you do?

Unless there’s a way to test and verify that it works or break then it’s hard to know

**Comment by XhmikosR** [comment]
@voxpelli the default is to use bash even on Windows, hence why this doesn't fail on CI. So, no, it's not default regarding the shell. But believe me, it does fail on Windows native cmd :)

**Comment by voxpelli** [comment]
That’s weird and unexpected :/ Then one can’t trust those tests really

**Comment by XhmikosR** [comment]
There's a reason behind this decision, as always.

But this doesn't change the thing that this change breaks things on Windows
native cmd.

If you guys consider it important, that's another thing. I personally
strive to keep Windows compatibility all these years, but either decision
is OK since this doesn't seem to affect the end users.

**Comment by voxpelli** [comment]
> As long as the tests still pass on Windows I’m 🙌

I mean, this was my review comment @XhmikosR

**Comment by bcomnes** [comment]
As a windows user worried about compatibility, it seems like wsl would be the better solution to this and for many of the other edge cases similar to this. Is this not accessible by default for some reason? (Sorry I haven't run windows in years). 

Also, as a dev time only dep, you would also need access to git, which would also seem to necessitate wsl or git bash. 

My goal is to cut down on everywhere deps when there are better solutions available because I get like 50+ prs when they major version.

**Comment by voxpelli** [comment]
@XhmikosR That bash is the default on windows seems to be incorrect? The [documentation](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#defaultsrunshell) says that this is the default:

> Windows `pwsh`
>
> This is the default shell used on Windows. The PowerShell Core. GitHub appends the extension .ps1 to your script name. If your self-hosted Windows runner does not have PowerShell Core installed, then PowerShell Desktop is used instead.
>
> `pwsh -command ". '{0}'".`

---

@bcomnes If you make a config like I did here you can opt to ignore such automated PR:s for specific dependencies: https://github.com/voxpelli/renovate-config/blob/main/ignores.json

---

Maybe we should restore some note in the docs? I'm okay with keeping the npm scripts as they are

**Pull request merged**
