### PR TITLE
Compatibility: npm, yarn and pnpm run scripts

### PR DESCRIPTION
**Pull request by ayu-exorcist**
Fix upstream issue: https://github.com/vuejs/create-vue/issues/393

Related PR: https://github.com/vuejs/create-vue/pull/394

### CODE REVIEW

**Comment by bcomnes** [comment]
Sorry can you clarify the issue here? In general my advise is: yarn, npm and pnpm have conflicting flag passing patterns in the scripts fields, and should not be used together. Pick one and stay consistent.

**Comment by bcomnes** [comment]
This seems fine. Let's try it out.

**Comment by ur5us** [comment]
@bcomnes Before this change, the following was working fine but is now broken:

```
"build:tailwindcss": "run-p 'build:tailwindcss:* {@}' --",
"build:tailwindcss:admin": "tailwindcss --postcss -i ./app/assets/stylesheets/admin/application.tailwind.css -o ./app/assets/builds/admin/application.css",
"build:tailwindcss:pages": "tailwindcss --postcss -i ./app/assets/stylesheets/application.tailwind.css -o ./app/assets/builds/application.css",
```

…and then called via `yarn build:tailwindcss -- --watch`

Am I missing something?

**Comment by bcomnes** [comment]
Ok good to know. I'll revert and take a closer look at the change.

**Comment by bcomnes** [comment]
I'm leaning to thinking this is probably a correct behavior change, but will likely need to go out in a breaking change. I didn't realize that earlier today. Sorry about that. 

Will take a closer look tomorrow and update tests to cover the breaking change.

**Comment by bcomnes** [comment]
@ayu-exorcist can you clarify the problem more? What do you need to do right now to get it to work? What doesn't work in that arrangement? What will we need to break to implement your behavior? Specific examples are helpful. I'm trying to read upstream but your insight will be helpful here as well.

**Comment by ayu-exorcist** [comment]
> "build:tailwindcss": "run-p 'build:tailwindcss:* {@}' --",

Please change `"run-p 'build:tailwindcss:* {@}' --"` to `"run-p 'build:tailwindcss:* -- {@}' --"`

**Comment by ur5us** [comment]
@ayu-exorcist No, that does not work!

**Comment by ayu-exorcist** [comment]
@bcomnes I don't familiar with `npm-run-all2`. Needs some help to proceed with the modifications.

@ur5us You need update `npm-run-all2` to v6.2.2

**Comment by bcomnes** [comment]
@ayu-exorcist just to clarify I reverted this change in v6.2.2 for now. If it goes in it needs to be a breaking change.

**Comment by ayu-exorcist** [comment]
> @ayu-exorcist just to clarify I reverted this change in v6.2.2 for now. If it goes in it needs to be a breaking change.

@bcomnes Yep, we need to have a provide unified command that is compatible with npm/yarn/pnpm double-dash.

**Comment by bcomnes** [comment]
Ok reading through this again. 

> This should be resolved in the upstream npm-run-all2

Here is my understanding:

- npm shipped with the ability to run scripts with arguments with the `npm run foo --  --args-go-here` originally. 
- Yarn ships the ability to run scripts with passed args while omitting `--`: `yarn run foo --args-go-here`, but also supported the `--` `yarn run foo -- --this-also-works`
- Pnpm you pass `pnpm run --args-go-here`. `pnpm` doesn't handle `--` in any special way (it just gets passed as a flag), meaning that its incompatible with the `npm` style of passing flags to scripts. 

Unfortunately this is the worst of all worlds. `yarn` introduces a cute omission feature with npm compatibility, pnpm adopts the cute omission pattern, but drops npm compatibility, and npm is what it is. In general, these tools are not interchangeable when it comes to writing run scripts. Pick a pattern, and assert which package manager you expect them to work with.  I'm guessing this is what people have worked around for quite a long time. 

So the breaking change here would be:

- Rewrite your run scripts to match the npm style `--` args passing, as the examples are written in the docs for nom-run-all2, even if you are running yarn or pnpm.
- The new version of npm-run-all2 would then strip these `--` args when run with yarn/pnpm
- In doing so, your run scripts that use npm-run-all2 would then work with any package manager. 

I'm going to have to think this over a bit more, since in general as mentioned, pick one and adjust is generally the most pragmatic approach. Trying to support all 3 at once opens up a ton of edge cases to deal with. Also people using yarn and pnpm probably have opinions about adding `--` where it's not conventional to do so.

**Comment by ur5us** [comment]
@bcomnes @ayu-exorcist Not sure whether it’s any helpful but here’s the issue when using `"run-p 'build:tailwindcss:* -- {@}' --"` on v6.2.1:
 
With the following in my `package.json`
```
"build:tailwindcss": "run-p 'build:tailwindcss:* -- {@}' --",
"build:tailwindcss:admin": "tailwindcss --postcss -i ./app/assets/stylesheets/admin/application.tailwind.css -o ./app/assets/builds/admin/application.css",
"build:tailwindcss:pages": "tailwindcss --postcss -i ./app/assets/stylesheets/application.tailwind.css -o ./app/assets/builds/application.css",
```
I then get this:
```
yarn build:tailwindcss --watch
yarn run v1.22.22
$ run-p 'build:tailwindcss:* -- {@}' -- --watch
$ tailwindcss --postcss -i ./app/assets/stylesheets/booking/application.tailwind.css -o ./app/assets/builds/booking/application.css {@}
$ tailwindcss --postcss -i ./app/assets/stylesheets/application.tailwind.css -o ./app/assets/builds/application.css {@}
```

Note the literal `{@}` at the end of command invocation. So the argument forwarding is not working. On v6.2.0 and now v6.2.2 where this change was reverted the `{@}` is properly substituted to `--watch`.

**Comment by ayu-exorcist** [comment]
image

`hasPlaceholder` value is false in `v6.2.1`. That's weird!!

**Comment by ayu-exorcist** [comment]
image

Solved it! More see: [RegExp/test in MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test)

**Comment by bcomnes** [comment]
@ur5us Just want to reiterate, you should have not had to change anything with this going in. Sorry about the disruption.

Moving discussion over to the new PR: https://github.com/bcomnes/npm-run-all2/pull/144

**Pull request merged**
